version: '3.1'
services:
  mysql:
    container_name: learningMysqlDB
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_USER=pek
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=learning
    volumes:
      - "./mysqldb:/var/lib/mysql"

